### ISSUE TITLE
invalid Unit

### ISSUE THREAD

**Issue by Tublick** [Herbycheck/arduino-dsmr#2]
Hi, 
thanks for your code! 
I use it in esphome because glmnet/Dsmr did not work (error Invalid Unit, mentioned in: https://github.com/esphome/issues/issues/3117)

now a similar issue here:
https://github.com/Herbycheck/arduino-dsmr/blob/c70b1811e146a1306046a9a4921b4ba32c9b043d/src/dsmr/fields.h#L263
Also Line: 264, 279, 280

im no programmer and for now a Github-noob! i hope this was an acceptable way to contact u.
i think, removing one "k" (units::kvarh, units::varh) should do the trick 

Best Regards

**Comment by Herbycheck** [comment]
Sorry I took so long to respond. Im not interested in maintaining this fork at the moment, sorry and good luck 🫡
